version: "3.3"

services:
    # postgres:
    #     image: postgres
    #     container_name: postgres_compose
    #     environment:
    #         POSTGRES_USER: mohamad
    #         POSTGRES_PASSWORD: 123321
    #         POSTGRES_DB: mohamad
    #     networks:
    #         - postgres
    #     expose:
    #         - 5432
    #     ports:
    #         - 5432:5432

    backend:
        # build: ./server/
        image: argus416/h3-facebook-clone-back
        container_name: backend_container
        expose:
            - 3001
        ports:
            - 3001:3001
        networks:
            - postgres
        volumes:
            - ./server:/app
            - /app/node_modules

        deploy:
            restart_policy:
                condition: on-failure 
                delay: 3s
                max_attempts: 10 
                window: 120s 
       
        # depends_on:
        #    - postgres

    frontend:
        # build: ./app/
        image: argus416/h3-facebook-clone-front
        container_name: frontend
        expose:
            - 3000
        ports:
            - 3000:3000
        networks:
            - postgres
        volumes:
            - ./app:/app
            - /app/node_modules
        deploy:
            restart_policy:
                condition: on-failure 
                delay: 3s 
                max_attempts: 3
                window: 120s
        depends_on: 
        - backend
        

networks:
    postgres:
        driver: bridge
