apiVersion: apps/v1
kind: Deployment
metadata:
  name: mohamad-facebook-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mohamad-facebook-backend
  template:
    metadata:
      labels:
        app: mohamad-facebook-backend
    spec:
      containers:
      - name: mohamad-facebook-backend
        image: argus416/h3-facebook-clone-back
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "256Mi"
---

apiVersion: v1
kind: Service
metadata:
  name: mohamad-facebook-backend
spec:
  selector:
    app: mohamad-facebook-backend
  ports:
  - port: 3001
    targetPort: 3001
  type: LoadBalancer
