apiVersion: v1
kind: Pod
metadata:
  name: mohamad-busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
  restartPolicy: Always