apiVersion: apps/v1
kind: Deployment
metadata:
  name: winn-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: winn-backend
  template:
    metadata:
      labels:
        app: winn-backend
    spec:
      containers:
      - name: winn-backend
        image: winnmbg/back_kube:0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "256Mi"
---

apiVersion: v1
kind: Service
metadata:
  name: winn-backend
spec:
  selector:
    app: winn-backend
  ports:
  - port: 80
    targetPort: 3001
  type: LoadBalancer
  
