name: Build and Push Docker Image
on: [push] 

jobs:
  build-and-push:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2  
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}  

      - name: Build and push Docker image frontend
        uses: docker/build-push-action@v3
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/h3-facebook-clone-front:latest

      - name: Build and push Docker image backend
        uses: docker/build-push-action@v3
        with:
            context: ./server
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/h3-facebook-clone-back:latest

  delete-kube-deployments:
    runs-on: ubuntu-latest 
    if: always()
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install kubectl
        run: sudo apt-get update && sudo snap install kubectl --classic

      - name: Install Azure CLI
        run: sudo apt-get -y update && sudo apt-get -y install azure-cli && az
      
      - name: Connect Azure Cloud
        run: az login --service-principal -u ${{ secrets.APPID }} -p ${{ secrets.AZ_SECRET }} --tenant ${{ secrets.TENANT_ID }}

      - name: Get Azure kubernetes cluster informations
        run: az aks get-credentials --resource-group hitema_kube --name hitema

      - name: Delete Kubernetes backend deployment
        run: kubectl delete -f ./k8s/backend.yaml

      - name: Delete Kubernetes frontend deployment
        run: kubectl delete -f ./k8s/frontend.yaml
    needs: [build-and-push]
        

  recreate-kube-deployments:
      runs-on: ubuntu-latest 
      steps:
        - name: Checkout repository code
          uses: actions/checkout@v4

        - name: Install kubectl
          run: sudo apt-get update && sudo snap install kubectl --classic
  
        - name: Install Azure CLI
          run: sudo apt-get -y update && sudo apt-get -y install azure-cli && az
        
        - name: Connect Azure Cloud
          run: az login --service-principal -u ${{ secrets.APPID }} -p ${{ secrets.AZ_SECRET }} --tenant ${{ secrets.TENANT_ID }}
  
        - name: Get Azure kubernetes cluster informations
          run: az aks get-credentials --resource-group hitema_kube --name hitema
          
        - name: Update Kubernetes backend deployment
          run: kubectl apply -f ./k8s/backend.yaml
  
        - name: Update Kubernetes frontend deployment
          run: kubectl apply -f ./k8s/frontend.yaml
      needs: [delete-kube-deployments]